<?php
/**
  DO NOT EDIT THIS FILE !!
  instead copy the local file cartmart_doofinder_local.php to your includes/languages/[english]/modules/cartmart folder and edit that one to override definitions here

  Doofinder addon for CE Phoenix Cart
  add smart search to your store
  author: @BrockleyJohn phoenix@cartmart.uk
  date: July 2024 
  copyright: SE Websites 2024
* released under MIT licence without warranty express or implied
*/

$pfx = 'MODULE_CARTMART_DOOFINDER_';
@include_once(__DIR__ . '/cartmart_doofinder_local.php');

$defs = [
  $pfx . 'TEXT_TITLE' => 'Doofinder Search',
  $pfx . 'TEXT_DESCRIPTION' => 'Add Doofinder to your search bar',

  // admin config texts
  $pfx . 'STATUS' . '_TITLE' => 'Module Status',
  $pfx . 'STATUS' . '_DESC' => 'Do you want to add Doofinder to your search bar?',
  $pfx . 'DOOF_SCRIPT' . '_TITLE' => 'Doofinder Script',
  $pfx . 'DOOF_SCRIPT' . '_DESC' => 'Copy the Doofinder script from your Doofinder account and paste it here',
  $pfx . 'SPIDER_SUPPRESS' . '_TITLE' => 'Suppress Spiders',
  $pfx . 'SPIDER_SUPPRESS' . '_DESC' => 'When set True, the Doofinder script will not be loaded for known spiders. This avoids getting charged for spider searches which will not result in a sale. Only works if you have Prevent Spider Sessions set True in your store sessions configuration (it\'s the default).',

  // admin validation
  $pfx . 'ERROR_SCRIPT_EMPTY' => 'Copy the Doofinder script from your Doofinder account',
  $pfx . 'ERROR_NO_SCRIPT_TAGS' => 'Paste the whole tag including <pre><script> and </script></pre>',
  $pfx . 'ERROR_SCRIPT_URL' => 'URL "%s" is not valid',
  $pfx . 'NO_LOAD_WITHOUT_SCRIPT' => 'The module will not load a script that appears invalid',
  $pfx . 'SCRIPT_OK' => 'Script appears to be valid',
];

foreach ($defs as $key => $val) {
  if (!defined($key)) {
    define($key, $val);
  }
}

